version: '3.9'

services:
  api:
    build:
      context: .
      target: development
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
    environment:
      DB_URI: postgres://postgres:password@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
